apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - kibishiiVKSStorageClass.yaml
patches:
  - path: windows-patch.yaml
    target:
      kind: StatefulSet
      group: apps
      version: v1
      name: kibishii-deployment
  - path: worker-image-patch.yaml
  - path: jump-pad-image-patch.yaml