apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: kibishii-deployment
spec:
  template:
    spec:
      tolerations:
      - effect: NoSchedule
        key: os
        operator: Equal
        value: windows
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: kibishii
        command: ["cmd.exe", "/c"]
        args: ["java -cp \"C:=\\Users\\ContainerUser\\*\" -jar C:\\Users\\ContainerUser\\kibishii.jar %POD_NAME% http://etcd-client:2379 C:\\Windows\\Temp"]
