FROM eclipse-temurin:8-jre

RUN mkdir -p /opt/share/kibishii

COPY opt/share/kibishii /opt/share/kibishii

RUN mkdir /data

CMD java -cp "/opt/share/kibishii/lib/*" -jar /opt/share/kibishii/kibishii.jar $HOSTNAME http://etcd-client:2379 /data
