apiVersion: v1
kind: Pod
metadata:
  name: jump-pad
spec:
  containers:
  - name: jump-pad
    image: velerobot4/jump-pad:main-362c5ab-07.05.2025.11.09.14
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - "ALL"
      seccompProfile:
        type: "RuntimeDefault"
      runAsUser: 65534
      runAsNonRoot: true
