apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: kibishii-deployment
spec:
  serviceName: "kibishii"
  selector:
    matchLabels:
      app: kibishii
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: kibishii
    spec:
      securityContext:
        fsGroup: 65534
      containers:
      - name: kibishii
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: gcr.io/velero-gcp/kibishii-worker:multi-arch-7414d31-29.Apr.2025.09.52.18
        volumeMounts:
        - name: kibishii-data
          mountPath: /data
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
          seccompProfile:
            type: "RuntimeDefault"
          runAsUser: 65534
          runAsNonRoot: true
  volumeClaimTemplates:
  - metadata:
      name: kibishii-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "kibishii-storage-class"
      resources:
        requests:
          storage: 50Mi
